/**
 * Foundational civilization event vocabulary.
 * Only publish when a real system action occurs — never fabricate.
 */

export const EventType = Object.freeze({
  // Economy
  ECONOMY_PRICE_CHANGE: "ECONOMY_PRICE_CHANGE",
  FOOD_SHORTAGE: "FOOD_SHORTAGE",
  SUPPLY_SHORTAGE: "SUPPLY_SHORTAGE",
  BUSINESS_OPENED: "BUSINESS_OPENED",
  BUSINESS_CLOSED: "BUSINESS_CLOSED",

  // Employment
  PLAYER_HIRED: "PLAYER_HIRED",
  PLAYER_FIRED: "PLAYER_FIRED",
  CITIZEN_HIRED: "CITIZEN_HIRED",
  CITIZEN_UNEMPLOYED: "CITIZEN_UNEMPLOYED",
  PROMOTION: "PROMOTION",

  // Government / Politics
  GOVERNMENT_CHANGE: "GOVERNMENT_CHANGE",
  POLICY_CHANGED: "POLICY_CHANGED",
  ELECTION_STARTED: "ELECTION_STARTED",
  ELECTION_COMPLETED: "ELECTION_COMPLETED",
  CANDIDATE_SELECTED: "CANDIDATE_SELECTED",

  // Emergency / Healthcare
  EMERGENCY_CREATED: "EMERGENCY_CREATED",
  EMERGENCY_RESOLVED: "EMERGENCY_RESOLVED",
  MEDICAL_TREATMENT_COMPLETED: "MEDICAL_TREATMENT_COMPLETED",

  // Infrastructure / Utilities / Logistics
  INFRASTRUCTURE_COMPLETED: "INFRASTRUCTURE_COMPLETED",
  UTILITY_FAILURE: "UTILITY_FAILURE",
  UTILITY_RESTORED: "UTILITY_RESTORED",
  SHIPMENT_STARTED: "SHIPMENT_STARTED",
  SHIPMENT_DELIVERED: "SHIPMENT_DELIVERED",

  // Player
  PLAYER_JOB_STARTED: "PLAYER_JOB_STARTED",
  PLAYER_JOB_ENDED: "PLAYER_JOB_ENDED",
  PLAYER_MISSION_COMPLETED: "PLAYER_MISSION_COMPLETED",
  PLAYER_CIVIC_CONTRIBUTION: "PLAYER_CIVIC_CONTRIBUTION",

  // Generic lifecycle (event manager)
  EVENT_SCHEDULED: "EVENT_SCHEDULED",
  EVENT_ANNOUNCED: "EVENT_ANNOUNCED",
  EVENT_ACTIVE: "EVENT_ACTIVE",
  EVENT_ACTIVE: "EVENT_ACTIVE",
  EVENT_COMPLETED: "EVENT_COMPLETED",
  FESTIVAL_STARTED: "FESTIVAL_STARTED",
  FESTIVAL_ENDED: "FESTIVAL_ENDED"
});

/** Types important enough to write civilization memory by default */
export const CIV_MEMORY_TYPES = new Set([
  EventType.FOOD_SHORTAGE,
  EventType.ELECTION_STARTED,
  EventType.ELECTION_COMPLETED,
  EventType.EMERGENCY_RESOLVED,
  EventType.INFRASTRUCTURE_COMPLETED,
  EventType.GOVERNMENT_CHANGE,
  EventType.PLAYER_CIVIC_CONTRIBUTION,
  EventType.FESTIVAL_STARTED,
  EventType.FESTIVAL_ENDED,
  EventType.UTILITY_FAILURE
]);

/** Types important enough to write citizen/player memory */
export const CITIZEN_MEMORY_TYPES = new Set([
  EventType.PLAYER_JOB_STARTED,
  EventType.PLAYER_JOB_ENDED,
  EventType.PLAYER_MISSION_COMPLETED,
  EventType.PLAYER_HIRED,
  EventType.PLAYER_FIRED,
  EventType.CITIZEN_HIRED,
  EventType.CITIZEN_UNEMPLOYED,
  EventType.PROMOTION,
  EventType.MEDICAL_TREATMENT_COMPLETED,
  EventType.PLAYER_CIVIC_CONTRIBUTION
]);
